import 'dart:async';
import 'dart:io';
import 'dart:typed_data';
import 'package:flutter/material.dart';
import 'package:screenshot/screenshot.dart';
import 'package:path_provider/path_provider.dart';
import '../models/name_slot.dart';

/// Draws the guest's name onto a copy of the template and returns PNG bytes.
///
/// This uses Flutter's own text renderer (via an off-screen widget + the
/// `screenshot` package) rather than a raw image-manipulation library, so
/// the exact font, size, and color you see in the designer screen is what
/// ends up on the generated card — no separate rendering engine to keep in sync.
class CardGeneratorService {
  static Future<Uint8List> generateCard({
    required BuildContext context,
    required File templateFile,
    required NameSlot slot,
    required double naturalWidth,
    required double naturalHeight,
    required String guestName,
  }) async {
    final controller = ScreenshotController();
    late OverlayEntry entry;
    final completer = Completer<Uint8List>();

    entry = OverlayEntry(
      builder: (_) => Positioned(
        left: -naturalWidth - 50, // keep it off-screen; still fully rendered
        top: 0,
        child: Screenshot(
          controller: controller,
          child: Material(
            color: Colors.transparent,
            child: SizedBox(
              width: naturalWidth,
              height: naturalHeight,
              child: Stack(
                children: [
                  Image.file(
                    templateFile,
                    width: naturalWidth,
                    height: naturalHeight,
                    fit: BoxFit.fill,
                  ),
                  Positioned(
                    top: slot.y - slot.fontSize / 2,
                    left: 0,
                    right: 0,
                    child: Center(
                      child: ConstrainedBox(
                        constraints: BoxConstraints(maxWidth: naturalWidth * slot.maxWidthRatio),
                        child: FittedBox(
                          fit: BoxFit.scaleDown,
                          child: Text(
                            guestName,
                            textAlign: TextAlign.center,
                            maxLines: 1,
                            style: TextStyle(
                              fontSize: slot.fontSize,
                              color: slot.color,
                              fontWeight: slot.bold ? FontWeight.bold : FontWeight.normal,
                              fontFamily: 'serif',
                            ),
                          ),
                        ),
                      ),
                    ),
                  ),
                ],
              ),
            ),
          ),
        ),
      ),
    );

    Overlay.of(context, rootOverlay: true).insert(entry);

    // Give the image + layout one frame (plus a small buffer) to settle
    // before capturing, since Image.file loads asynchronously.
    await WidgetsBinding.instance.endOfFrame;
    await Future.delayed(const Duration(milliseconds: 120));

    final bytes = await controller.capture(pixelRatio: 1.0);
    entry.remove();

    if (bytes == null) {
      throw Exception('Could not render the card. Try again.');
    }
    return bytes;
  }

  /// Saves generated bytes to a temp file so it can be handed to WhatsApp's
  /// share intent (which needs a real file, not raw bytes).
  static Future<File> saveToTempFile(Uint8List bytes, String fileName) async {
    final dir = await getTemporaryDirectory();
    final file = File('${dir.path}/$fileName');
    await file.writeAsBytes(bytes);
    return file;
  }
}
